# Render Blueprint for deploying the FastAPI backend and a managed Postgres database

databases:
  - name: rag-db
    databaseName: rag_database
    plan: free

services:
  - type: web
    name: rag-backend
    env: python
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /health

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: uvicorn app.main_simple:app --host 0.0.0.0 --port $PORT

    envVars:
      # DATABASE_URL will automatically reference the managed Postgres instance above
      - key: DATABASE_URL
        fromDatabase:
          name: rag-db
          property: connectionString

      # Frontend URLs for CORS
      - key: ALLOWED_ORIGINS
        value: https://rag-nextjs-frontend.vercel.app,https://rag-nextjs.vercel.app

      # Optional: Qdrant configuration. Set these securely in Render Dashboard env vars if used.
      # - key: QDRANT_URL
      #   value: <your-qdrant-url>
      # - key: QDRANT_API_KEY
      #   value: <set-in-render-dashboard>

      # Optional: turn off non-essential features in hosted environment by default
      - key: MCP_SERVER_ENABLED
        value: "false"
      - key: WEB_SEARCH_ENABLED
        value: "true"
