# Render Blueprint for deploying the FastAPI backend and a managed Postgres database

databases:
  - name: rag-db
    databaseName: rag_database
    plan: free

services:
  - type: web
    name: rag-backend
    env: python
    rootDir: backend
    plan: free
    autoDeploy: true
    healthCheckPath: /health

    buildCommand: |
      pip install --upgrade pip
      pip install poetry
      poetry config virtualenvs.create false
      poetry install --no-interaction --no-ansi --without dev

    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT

    envVars:
      # DATABASE_URL will automatically reference the managed Postgres instance above
      - key: DATABASE_URL
        fromDatabase:
          name: rag-db
          property: connectionString

      # Optional: provide your Google API key
      - key: GOOGLE_API_KEY
        value: AIzaSyBJ344Y5VK4zBN2qNqQI3CC8E9fY7iJkFE

      # Optional: set ALLOWED_ORIGINS to your frontend URL(s), comma-separated
      - key: ALLOWED_ORIGINS
        value: https://rag-nextjs-frontend.vercel.app

      # Optional: Qdrant configuration (leave blank if not using Qdrant Cloud yet)
      - key: QDRANT_URL
        value: http://localhost:6333
      - key: QDRANT_API_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhY2Nlc3MiOiJtIn0.2baXI6tKhqem1i057dI3sN9hmhEaINag1ys4_BcE32w

      # Optional: turn off non-essential features in hosted environment by default
      - key: MCP_SERVER_ENABLED
        value: "false"
      - key: WEB_SEARCH_ENABLED
        value: "true"
